# Transformação Homogênea

In [2]:
import numpy as np

In [3]:
q = np.matrix('0 ; 3; 2')
q

matrix([[0],
        [3],
        [2]])

In [4]:
Rab = np.matrix('1 0 0; 0 0 1; 0 -1 0')
Rab

matrix([[ 1,  0,  0],
        [ 0,  0,  1],
        [ 0, -1,  0]])

In [5]:
T = np.matrix('1 0 0 0; 0 0 -1 3; 0 1 0 2; 0 0 0 1')
T

matrix([[ 1,  0,  0,  0],
        [ 0,  0, -1,  3],
        [ 0,  1,  0,  2],
        [ 0,  0,  0,  1]])

In [6]:
Pb = np.matrix('0;1;1;1')
Pb

matrix([[0],
        [1],
        [1],
        [1]])

In [7]:
Pa = np.dot(T,Pb)
Pa = Pa[0:3]
Pa

matrix([[0],
        [2],
        [3]])